export enum FileUploadExtensions {
  PDF = 'pdf',
  WORD_DOC = 'doc',
  WORD_DOCX = 'docx',
  IMAGE_PNG = 'png',
  IMAGE_JPG = 'jpg',
  IMAGE_JPGEG = 'jpeg',
  IMAGE_GIF = 'gif',
  IMAGE_WEBP = 'webp',
  VIDEO_MP4 = 'mp4',
  VIDEO_WEBM = 'webm',
  VIDEO_MKV = 'mkv',
  VIDEO_3GP = '3gp',
  VIDEO_AVI = 'avi',
  VIDEO_WMV = 'wmv',
  VIDEO_MOV = 'mov',
  VIDEO_M3U8 = 'm3u8',
  VIDEO_TS = 'ts',
  VIDEO_FLV = 'flv',
}
